refactor(components): rename prop in Button
```
error TS2745: This JSX tag's 'children' prop expects type 'string' which requires multiple children, but only a single child was provided.
```